image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.2"
  ANDROID_SDK_TOOLS:   "4333796"

before_script:

stages:
  - build
  - protectAndUpload
  - sendMail


assembleRelease:
  stage: build
  script:
    - npm install
    - chmod +x ./gradlew
    - export CI_COMMIT_TAG=$CI_PIPELINE_ID
    - ./gradlew assembleRelease
  artifacts:
    paths:
    - app/build/outputs/
  only:
        - master
        - dev
  tags:
    - ios


protectAndUpload:
  stage: protectAndUpload
  script:
    - chmod +x ./gitlab_ci/protectAndUpload
    - ./gitlab_ci/protectAndUpload
#  artifacts:
#    paths:
#      - app/build/outputs/apk/release/
  retry: 2
  only:
        - master
        - dev
  tags:
    - ios



sendMail:
 stage: sendMail
 script:
   - chmod +x ./gitlab_ci/sendMail.py
   - python ./gitlab_ci/sendMail.py
 dependencies: []
 only:
         - master
         - dev
 tags:
     - ios


#debugTests:
#  stage: test
#  script:
#   - ./gradlew -Pci --console=plain :app:testDebug